# -*- coding: utf-8 -*-
"""Test BackEnd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIRSXNocYLcaJ_C4BmszgkxF1gaA54Ao
"""

def hitung_gaji():
    try:
        # Meminta input dari pengguna
        jam_kerja = float(input("Masukkan jumlah jam kerja dalam seminggu: "))
        tarif_per_jam = float(input("Masukkan tarif per jam: "))

        # Menentukan jumlah jam lembur jika ada
        jam_normal = 40
        if jam_kerja > jam_normal:
            jam_lembur = jam_kerja - jam_normal
        else:
            jam_lembur = 0

        # Menghitung gaji
        gaji_normal = min(jam_kerja, jam_normal) * tarif_per_jam
        gaji_lembur = jam_lembur * tarif_per_jam * 1.5
        total_gaji = gaji_normal + gaji_lembur

        # Menampilkan hasil
        print(f"Gaji normal: Rp{gaji_normal:.2f}")
        print(f"Gaji lembur: Rp{gaji_lembur:.2f}")
        print(f"Total gaji: Rp{total_gaji:.2f}")

    except ValueError:
        print("Input tidak valid. Masukkan angka untuk jam kerja dan tarif per jam.")

# Memanggil fungsi
hitung_gaji()